// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistracijaApp.Data;

namespace RegistracijaApp.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RegistracijaApp.Models.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            QuestionId = 1,
                            Value = "Taip"
                        },
                        new
                        {
                            Id = 2,
                            QuestionId = 1,
                            Value = "Ne"
                        },
                        new
                        {
                            Id = 3,
                            QuestionId = 2,
                            Value = "Metinis rangovas"
                        },
                        new
                        {
                            Id = 4,
                            QuestionId = 2,
                            Value = "Nenuolatinis rangovas"
                        },
                        new
                        {
                            Id = 5,
                            QuestionId = 3,
                            Value = "Taip"
                        },
                        new
                        {
                            Id = 6,
                            QuestionId = 3,
                            Value = "Ne"
                        },
                        new
                        {
                            Id = 7,
                            QuestionId = 4,
                            Value = "Automatinis"
                        },
                        new
                        {
                            Id = 8,
                            QuestionId = 4,
                            Value = "Rankinis"
                        },
                        new
                        {
                            Id = 9,
                            QuestionId = 5,
                            Value = ""
                        },
                        new
                        {
                            Id = 10,
                            QuestionId = 5,
                            Value = "VIP"
                        });
                });

            modelBuilder.Entity("RegistracijaApp.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Reikia atlikti rangos darbus"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Rangos darbus atliks"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Verslo klientas"
                        },
                        new
                        {
                            Id = 4,
                            Title = "Skaičiavimo metodas"
                        },
                        new
                        {
                            Id = 5,
                            Title = "Svarbus klientas"
                        });
                });

            modelBuilder.Entity("RegistracijaApp.Models.Answer", b =>
                {
                    b.HasOne("RegistracijaApp.Models.Question", "Questions")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("RegistracijaApp.Models.Question", b =>
                {
                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
